### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pedrohma95** [jamesdaniels/onSnapshot#2]
I'm trying to access the link: https://onsnapshot.com/ but it shows **504 Gateway Time-out**. Any ideas of what is happening?

![image](https://user-images.githubusercontent.com/6583751/37668237-35ff1aa6-2c21-11e8-84e9-9f4d52eaf3fd.png)

**Comment by jamesdaniels** [comment]
Seems like you found it, but just adding incase anyone else runs into this. Having a problem with the Cloud Functions deployment, I have it up on Flex here though http://onsnapshot-flex.appspot.com/
